.TH cool-retro-term 1 "August 22 2016"
.SH NAME
cool-retro-term \- terminal emulator mimicing the old cathode display
.SH SYNOPSIS
"Usage: ./cool\-retro\-term [\-\-default\-settings] [\-\-workdir <dir>] [\-\-program <prog>] [\-p|\-\-profile <prof>] [\-\-fullscreen] [\-h|\-\-help]"
.SH DESCRIPTION
This manual page documents briefly the
.B cool-retro-term
command.
.SH OPTIONS
.TP
\fB\-\-default\-settings\fR
Run cool\-retro\-term with the default settings
.TP
\fB\-\-workdir\fR <dir>
Change working directory to 'dir'
.TP
\fB\-e\fR <cmd>
Command to execute. This option will catch all following arguments, so use it as the last option.
.TP
\fB\-\-fullscreen\fR
Run cool\-retro\-term in fullscreen.
.HP
\fB\-p\fR|\-\-profile <prof> Run cool\-retro\-term with the given profile.
.TP
\fB\-h\fR|\-\-help
Print this help.
.TP
\fB\-\-verbose\fR
Print additional informations such as profiles and settings.
.PP
