.TH "COOL-RETRO-TERM" 1 "2017-11-06"
.SH NAME
cool\-retro\-term \- terminal emulator mimicking an old cathode display
.SH SYNOPSIS
\fBcool\-retro\-term\fR [\fIOPTIONS\fR]
.br
\fBcool\-retro\-term\fR [\fIOPTIONS\fR] -e \fICOMMAND\fR [\fIARGUMENT\fR...]
.SH DESCRIPTION
This manual page documents briefly the \fBcool\-retro\-term\fR command.
.PP
\fBcool\-retro\-term\fR is a terminal emulator which mimics the
look and feel of the old cathode tube screens.
It has been designed to be eye-candy,
customizable, and reasonably lightweight.
.SH OPTIONS
.TP
\fB\-\-default\-settings\fR
Run with the default settings.
.TP
\fB\-e\fR \fICOMMAND\fR
Command to execute. This should be used as the last option.
All the arguments following \fICOMMAND\fR will be passed to said command.
.TP
\fB\-\-fullscreen\fR
Run in fullscreen mode.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a help screen and exit.
.TP
\fB\-p\fR \fIPROFILE\fR, \fB\-\-profile\fR \fIPROFILE\fR
Run with the given profile.
.TP
\fB\-T\fR \fITITLE\fR
Use \fITITLE\fR as the window title.
.TP
\fB\-\-verbose\fR
Print additional information such as profiles and settings.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print the version number and exit.
.TP
\fB\-\-workdir\fR \fIDIR\fR
Start with \fIDIR\fR as the working directory.
.SH LICENCE
This program is available under the terms of the GNU General Public License,
version 3 or any later version, as published by the Free Software Foundation.
